### ISSUE TITLE
invalid jsonType: time.Time

### ISSUE THREAD

**Issue by ssmall** [santhosh-tekuri/jsonschema#115]
It does not seem possible to validate schemas that contain strings with format `date` as they will automatically get unmarshaled into a Go `time.Time` and validation will fail with the message:

```
jsonschema: invalid jsonType: time.Time
```

The code on this Go Playground illustrates the issue: https://go.dev/play/p/Q1ciGF5PE5Y

Is this a bug with schema validation, or expected behavior? If it is expected behavior, is there a workaround to allow validating documents that contain date-formatted strings?

Thanks!

**Comment by santhosh-tekuri** [comment]
this is the expected behaviour;

the [documentation](https://github.com/santhosh-tekuri/jsonschema/blob/7895cf279d0b176c087dd31ce020aaa9bf294857/schema.go#L159) clearly says value must be raw json value

i.e it must be string, boolean, number, map, array and composite of these.

in your case yaml unmarshalled it into `time.Time`. you unmarshal that value into string.

**Comment by ssmall** [comment]
There's actually no way to control this behavior. It is the default behavior of the YAML unmarshaler when unmarshaling to `any`. Please reopen and consider a fix.

**Comment by santhosh-tekuri** [comment]
if you have used quotes around the value then it will get converted into string:

```go
yamlString := `date: "2025-01-01"`
```
