### ISSUE TITLE
`URLLoader.Load()` should pass the original URL

### ISSUE THREAD

**Issue by raphaelyancey** [santhosh-tekuri/jsonschema#193]
I'm trying to load a schema from `//go:embed` and thus needed to define a new loader.

The problem is that the URL passed to the custom loader is not the same as the one passed to `Compile()` and makes it difficult.

Original URL: `instance_schema.json`
URL passed to `Load()`: `file:///absolute/path/to/instance_schema.json`

**Comment by santhosh-tekuri** [comment]
this is the expected behaviour:

`URLLoader.Load` takes absolute URL. since you have given relative url to `Compile` it is converted to absolute url before passing to `URLLoader`. if you give absolute URL to `Compile` it is passed as it is to `URLLoader`

I would suggest to give something line `embed://instance_schema.json` to compile and trim prefix `embed://` inside your `URLLoader` implementation

**Comment by raphaelyancey** [comment]
Okay, I finally used this

```go
rawSchema, err := schemas.ReadFile(schemaPath)
if err != nil {
	return err
}

schema, err := jsonschema.UnmarshalJSON(bytes.NewReader(rawSchema))
if err != nil {
	return err
}

if err := compiler.AddResource("schema.json", schema); err != nil {
	return err
}

compiledSchema, err := compiler.Compile("schema.json")
if err != nil {
	return err
}
```

A bit divergent from the original idea but it works fine!
